<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>info</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="css/red.css" />
</head>
<body class="grey lighten-3">
<nav>
<div class="nav-wrapper light-blue darken-4">
            <a href="/" class="brand-logo"><img src="img/CVmaker-logo.png" alt="logo" id="title"></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/info">Info</a></li>
                <li><a href="/getstarted">Get started</a></li>
                <li><a href="/aboutus">About us</a></li>
            </ul>
        </div>
</nav>
<div style="margin-top:30px;">
    <div class="container">
        <div class="container">
            <div class="row">
                <div class="card white">
                    <div class="card-content black-text">
                    <span class="card-title red-text"><h3>About Us</h3></span>
                    <p>
                    <h5>About CV maker</h5>
                    <p>The majority of people find it hard to draw up a good CV. 
                    Our project started with the idea of making a good CV easy and accessible for everyone. 
                    With our CV maker you can make up a professional CV in 3 steps and in just 10 minutes.</p>
                    <div id="team" class="section scrollspy">
        <h2 class="header">Meet the Team</h2>
        <p class="caption">We are a team of students from VIVES Brugge.</p>
        <div class="center">
          <div class="image-container">
            <img src="img/vives_building.jpg" style="width:100%;">
          </div>
        </div>
        <br />

        <div class="row">
          <div class="col s12 m3 center-on-small-only">
            <div class="image-container">
              <img class="circle" width= "150px" height="150px" src="img/Captain_America.jpg">
              </div>
          </div>
          <div class="col s12 m9">
            <h4>Jop Bouckaert</h4>
            <p>!Description here
            <blockquote>"I can do this all day." <br> &nbsp -Steve Rogers</blockquote>
            </p>
            
          </div>
        </div>

        <div class="row">
          <div class="col s12 m3 center-on-small-only">
            <div class="image-container">
              <img class="circle" width= "150px" height="150px" src="img/Spiderman.jpg">
              </div>
          </div>
          <div class="col s12 m9">
            <h4>Frederik Feys</h4>
            <p>!Description here
            <blockquote>“If you’re nothing without that suit, then you shouldn’t have it.” <br> &nbsp -Tony Stank</blockquote>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col s12 m3 center-on-small-only">
            <div class="image-container">
              <img class="circle" width= "150px" height="150px" src="img/Hulk.jpg">
              </div>
          </div>
          <div class="col s12 m9">
            <h4>Jurne Decadt</h4>
            <p>!Description here
            <blockquote>“Hulk always... always angry.” <br> &nbsp -Bruce Banner</blockquote>
            </p>
          </div>
        </div>
                    </p>
                </div>
            </div>
      </div>
        </div>
    </div>
</div>


<footer class="page-footer light-blue darken-4">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Curriculum Vitae</h5>
                <p class="white-text">This site is made possible by the slim framework, Vue.JS, materialize.</p>
                <p class="white-text">You can view our code on our GitHub.</p>
                <a><img src="img/JFJ-logo.png"></a>
            </div>
            <div class="col l2 offset-l4">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="https://materializecss.com/" target="_blank"><img
                                src="img/materialize.png"></a></li>
                    <li><a class="grey-text text-lighten-3" href="https://vuejs.org/" target="_blank"><img src="img/Vue.js_Logo.svg.png"
                                width="32px" height="32px"></a></li>
                    <li><a class="grey-text text-lighten-3" href="https://www.slimframework.com/" target="_blank"><img
                                src="img/slimphp-logo.png" width="32px" height="32px"></a></li>
                    <li><a class="grey-text text-lighten-3" href="https://github.com/vives-webapplications-2018/vue-project-cv-maker-jfj"
                            target="_blank"><img src="img/github-logo.png"></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2018 JFJ
        </div>
    </div>
</footer>
</body>
</html>