<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>vb CV</title>
    <link rel="stylesheet" href="css/cv.css">
</head>
<body>
    <aside class="left">
        <h1 class="naam">Jurne Decadt</h1>

        <h1>Personalia</h1>

        <h2>Naam</h2>
        <p>Jurne Decadt</p>
        
        <h2>Adres</h2>
        <p>Meulebekestraat 42</p>
        <p>8740 Pittem</p>
        
        <h2>Telefoonnummer</h2>
        <p>0478/03 10 97</p>
        
        <h2>E-mailadres</h2>
        <p>jurne.decadt@gmail.com</p>
        
        <h2>Geboortedatum</h2>
        <p>25/08/1999</p>
        
        <h2>Geslacht</h2>
        <p>man</p>
        
        <h2>Rijbewijs</h2>
        <p>B</p>
        
        <h2>github</h2>
        
        <h1>Intresses</h1>

        <h2>Talen</h2>
        <p>html </p>
        <p>css </p>

    </aside>
    <section>
        <h1>Opleidingen</h1>
        <p class="school">Vives</p>
        <p class="richting">ICT</p>

    </section>
    <section>
        <h1>Werkervaring</h1>
    </section>

    <section>
        <h1>Certificaten</h1>
    </section>
    
    <section>
        <h1>Vaardigheden</h1>
    </section>
</body>
</html>