<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>info</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="css/red.css" />
</head>

<body class="grey lighten-3">
    <nav>
        <div class="nav-wrapper light-blue darken-4">
            <a href="/" style="margin:10px;" class="brand-logo"><img src="img/CVmaker-logo.png" alt="logo"></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/info">Info</a></li>
                <li><a href="/getstarted">Get started</a></li>
                <li><a href="/aboutus">About us</a></li>
            </ul>
        </div>
    </nav>
    <div style="margin-top:30px;">
        <div class="container">
            <div class="container">
                <div class="row">
                    <div class="card white">
                        <div class="card-content black-text">
                            <span class="card-title red-text">
                                <h3>Get started</h3>
                            </span>
                            <ul class="collapsible">
                                <li>
                                    <div class="collapsible-header">
                                        <i class="large material-icons red-text">account_circle</i>
                                        1. Personal information <br>
                                        In the first step you have to fill in the form with your personal information.
                                    </div>
                                </li>
                                <li>
                                    <div class="collapsible-header">
                                        <i class="large material-icons red-text">flash_on</i>
                                        2. Skills<br>
                                        The next step is about your skills. There you fill in the skills you have and
                                        give them a quotation.
                                    </div>
                                </li>
                                <li>
                                    <div class="collapsible-header">
                                        <i class="large material-icons red-text">cloud_download</i>
                                        3. Get your CV! <br>
                                        Here you can view your CV in an online template.
                                    </div>
                                </li>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <footer class="page-footer light-blue darken-4">
            <div class="container">
                <div class="row">
                    <div class="col l6 s12">
                        <h5 class="white-text">Curriculum Vitae</h5>
                        <p class="white-text">This site is made possible by the slim framework, Vue.JS, materialize.</p>
                        <p class="white-text">You can view our code on our GitHub.</p>
                        <a><img src="img/JFJ-logo.png"></a>
                    </div>
                    <div class="col l2 offset-l4">
                        <h5 class="white-text">Links</h5>
                        <ul>
                            <li><a class="grey-text text-lighten-3" href="https://materializecss.com/" target="_blank"><img
                                        src="img/materialize.png"></a></li>
                            <li><a class="grey-text text-lighten-3" href="https://vuejs.org/" target="_blank"><img src="img/Vue.js_Logo.svg.png"
                                        width="32px" height="32px"></a></li>
                            <li><a class="grey-text text-lighten-3" href="https://www.slimframework.com/" target="_blank"><img
                                        src="img/slimphp-logo.png" width="32px" height="32px"></a></li>
                            <li><a class="grey-text text-lighten-3" href="https://github.com/vives-webapplications-2018/vue-project-cv-maker-jfj"
                                    target="_blank"><img src="img/github-logo.png"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    © 2018 JFJ
                </div>
            </div>
        </footer>
</body>

</html>