<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>info</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>
<body class="grey lighten-3">
<nav>
    <div class="nav-wrapper light-blue darken-4">
        <a href="#" style="margin:10px;" class="brand-logo"><img src="img/CVmaker-logo.png" alt="logo"></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/info">Info</a></li>
            <li><a href="/getstarted">Get started</a></li>
            <li><a href="#">About us</a></li>
        </ul>
    </div>
</nav>
<div style="margin-top:30px;">
    <div class="container">
        <div class="container">
            <div class="row">
                <div class="card white">
                    <div class="card-content black-text">
                    <span class="card-title">CV maker</span>
                    <p>CV maker is an online form that you can fill in to create your own CV. 
                        We made it as easy as possible to fill in, so everybody even if you don't have any experience with making a CV, can make one.
                        There are three major steps in making your CV.
                        You just have to follow the steps and in a matter of time you created your own CV.
                    <img src="img/cvvoorbeeld.jpg" alt="example" height="80%" width="80%">
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>


<footer class="page-footer light-blue darken-4">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Curriculum Vitae</h5>
                <p class="white-text">This site is made possible by the slim framework, Vue.JS, materialize.</p>
                <p class="white-text">You can view our code on our GitHub.</p>
                <a><img src="img/JFJ-logo.png"></a>
            </div>
            <div class="col l2 offset-l4">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="https://materializecss.com/" target="_blank"><img
                                src="img/materialize.png"></a></li>
                    <li><a class="grey-text text-lighten-3" href="https://vuejs.org/" target="_blank"><img src="img/Vue.js_Logo.svg.png"
                                width="32px" height="32px"></a></li>
                    <li><a class="grey-text text-lighten-3" href="https://www.slimframework.com/" target="_blank"><img
                                src="img/slimphp-logo.png" width="32px" height="32px"></a></li>
                    <li><a class="grey-text text-lighten-3" href="https://github.com/vives-webapplications-2018/vue-project-cv-maker-jfj"
                            target="_blank"><img src="img/github-logo.png"></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2018 JFJ
        </div>
    </div>
</footer>
</body>
</html>