<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>CV maker</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <link rel="stylesheet" href="css/red.css" />
</head>

<body class="grey lighten-3">
    <nav>
        <div class="nav-wrapper light-blue darken-4">
            <a href="/" style="margin:10px;" class="brand-logo"><img src="img/CVmaker-logo.png" alt="logo"></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/info">Info</a></li>
                <li><a href="/getstarted">Get started</a></li>
                <li><a href="/aboutus">About us</a></li>
            </ul>
        </div>
    </nav>

    <footer class="page-footer light-blue darken-4">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Curriculum Vitae</h5>
                    <p class="white-text">This site is made possible by the slim framework, Vue.JS, materialize.</p>
                    <p class="white-text">You can view our code on our GitHub.</p>
                    <a><img src="img/JFJ-logo.png"></a>
                </div>
                <div class="col l2 offset-l4">
                    <h5 class="white-text">Links</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="https://materializecss.com/" target="_blank"><img
                                        src="img/materialize.png"></a></li>
                        <li><a class="grey-text text-lighten-3" href="https://vuejs.org/" target="_blank"><img src="img/Vue.js_Logo.svg.png"
                                        width="32px" height="32px"></a></li>
                        <li><a class="grey-text text-lighten-3" href="https://www.slimframework.com/" target="_blank"><img
                                        src="img/slimphp-logo.png" width="32px" height="32px"></a></li>
                        <li><a class="grey-text text-lighten-3" href="https://github.com/vives-webapplications-2018/vue-project-cv-maker-jfj"
                                    target="_blank"><img src="img/github-logo.png"></a></li>
                    </ul>
                </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    © 2018 JFJ
                </div>
            </div>
    </footer>